#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

OriginalTestDir=../../../LSTM/FullUtterance
ConfigDir=$TEST_DIR/../../../ExperimentalHtkmlfReader/LSTM/FullUtterance

(cd $TEST_DIR/$OriginalTestDir && md5sum baseline*) | (cd $TEST_DIR && md5sum --status -c -)
if [ $? != 0 ]; then
  echo Error: Baselines must match original test. Copy from $OriginalTestDir.
  exit 1
fi

# cntkrun <CNTK config file name> <additional CNTK args>
cntkrun cntk.cntk 'Truncated=false speechTrain=[SGD=[epochSize=2560]] speechTrain=[SGD=[maxEpochs=2]] speechTrain=[SGD=[numMBsToShowResult=1]] shareNodeValueMatrices=true' || exit $?
